Revert "Revert "Revert "Make sure that const-class linkage is preserved."""
626-const-class-linking is failing (spurious wakeups?)
970-iface-super-resolution-gen is failing:
    dex2oatd F 11-24 10:57:16  6410  6410 image_writer.cc:1144]
    Check failed: !IsBootClassLoaderClass(as_klass)
    java.lang.Class<java.lang.NoSuchMethodError>

Bug: 30627598

This reverts commit 25dcbad4462ea7279ee2bbe0884abc25bdfac77a.

Change-Id: Ie010169bdde45e6ccf2e04a521da4682bd817114