Revert "build: Generate asm_support_gen.h from the build, validate up-to-date"
Breaks the build bot:

error: art/tools/cpp-define-generator/Android.bp:41:1: dependency "cpp-define-generator-data" of "cpp-define-generator-asm-support" missing variant "arch:linux_x86_64"

This reverts commit 2449a154c457eaa2c6a30e11184bb7381903cfd5.

Change-Id: I05ae3fa3c56a10238d48c52faa10b8c9c82d9d24